# Generated by Django 4.1.7 on 2023-04-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_ecoponto", "0002_descartadores"),
    ]

    operations = [
        migrations.AddField(
            model_name="descartadores",
            name="ENDERECO",
            field=models.CharField(default="-", max_length=15),
        ),
    ]
